spring.application.name=HariOm-1

spring.datasource.url=jdbc:mysql://localhost:3306/Arnav?CreateDatabsaeIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
server.port=9090

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true